---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:11.0.1"
  armhf: "ghcr.io/hassio-addons/base/armhf:11.0.1"
  armv7: "ghcr.io/hassio-addons/base/armv7:11.0.1"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:11.0.1"
